import collections
import csv
counter1=collections.Counter(['a','a','b','b','b','c'])
print(counter1)
print(counter1.elements())
print(counter1.most_common())
counter1['a']=0
print(counter1)
del(counter1['a'])
print(counter1)
counter1["a"]=2
print(counter1)

deque1=collections.deque([1,2,3,4,5,6])
print(deque1)
#print(maxlen(deque1))
deque1.append(7)
print(deque1)
#print(maxlen(deque1))
deque1.appendleft(0)
print(deque1)
#print(deque1.maxlen())
deque1.extend('89')
print(deque1)
#print(deque1.maxlen())
deque1.extendleft('-12')
print(deque1)
#print(deque1.maxlen())
deque1.remove('-')
deque1.remove('1')
deque1.remove('2')
print(deque1)
deque1.pop()
print(deque1)
deque1.popleft()
print(deque1)
print(deque1.count(0))
deque1.insert(8,9)
print(deque1)
deque1.rotate(2)
print(deque1)
deque1.rotate(-1)
print(deque1)
deque1.clear()
print(deque1)

scoresList=[("A",10),("B",20),("C",30)]
defaultdict1=collections.defaultdict(list)
for i,j in scoresList:
    defaultdict1[i].append(j)
print(defaultdict1.items())
print(defaultdict1['A'])
print(defaultdict1)
del(defaultdict1["C"])
print(defaultdict1)

employee=collections.namedtuple("Employee","id,name,age,designation")
e1=employee(id=1,name="Shubham",designation="Student",age=21)
print(e1)
print(e1.name)
print(e1.age)
# Employee=collections.namedtuple("Employee","name,age")
# for e in map(Employee._make,csv.reader(open("employee.csv","rb"))):
#     print(e.name)
#     print(e.age)

ordereddict1=collections.OrderedDict({"a":1,"b":2,"c":3})
print(ordereddict1)
print ("Done")