import os
fn=open("file.txt","r+")
print(fn.name)
print(fn.closed)
print(fn.mode)
str=fn.read(1)
print(str)
str=fn.readline()
print(str)
print("Done till readline")
str=fn.readlines()
print(str)
print("Done till readlines")
fn.close()
os.rename("file.txt","file1.txt")
os.remove("file1.txt")
f=open("file1.txt","a+")
f.write('Line 1 of file\nLine 2 of file')
f.seek(0)
str=f.read(10)
print(str)
f.write("\nLine 3 of file")
f.write('\nLast line of file')
print(f)
str=f.readlines()
print(str)